import { GovernedProgramShell } from "./experience-lab";
import { AnalyteTable, CheckoutStepIndicator, CustodyTimeline, RecommendationCard, ReportIdentityHeader, RestockCard, UnavailableEvidencePanel, UpsellContextRail, type CheckoutStep } from "./design-system/program-components";
import { canOpenOriginal, exactPurityAverage, mk2866OpenLabProjection, reportCount } from "./design-system/openlab-authority";
import { CurrencyEqualityLock, LifecycleAmountRecord, PaymentTrustPrimer } from "./design-system/payment-trust";
import { paymentTrustCopy, paymentTrustStudy } from "./design-system/payment-trust-contract";
import styles from "./program-routes.module.css";

function Hero({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <section className={styles.hero}><div className={styles.shell}><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div></section>; }
function Card({ title, copy, children }: { title: string; copy: string; children?: React.ReactNode }) { return <article className={styles.card}><h2>{title}</h2><p>{copy}</p>{children}</article>; }

export function OpenLabCompoundPage({ slug }: { slug: string }) { const known=slug === "mk-2866"; const reports=known?[mk2866OpenLabProjection]:[]; const average=exactPurityAverage(reports); return <GovernedProgramShell><Hero eyebrow="OPENLAB · COMPOUND" title={known ? "MK-2866 / Ostarine" : "Compound record unavailable"} copy="Commercial identity and analytical specimen identity remain separate. This dossier never infers a result from catalogue copy."/><section className={styles.section}><div className={`${styles.shell} ${styles.grid}`}><ReportIdentityHeader state={known?"source-reported":"unavailable"}/><Card title="Report coverage" copy={`${reportCount(reports)} report-level record. Multi-analyte rows do not increase this count.`}/><AnalyteTable rows={mk2866OpenLabProjection.analytes.map(({analyte,value,unit})=>({analyte,value:String(value),unit}))}/><CustodyTimeline/><Card title="Purity history" copy={average === null ? "The source-owned value is a threshold (>99%), so no exact-value average is calculated." : `Exact-value average: ${average}%`}/>{canOpenOriginal(mk2866OpenLabProjection)?<a className={styles.button} href={mk2866OpenLabProjection.reportSource.value!}>Open original source</a>:<UnavailableEvidencePanel title="Original source unavailable" copy="No registered source URL or PDF is available for this report-level record."/>}<RecommendationCard state="default"/></div></section></GovernedProgramShell>; }

export function OpenLabReportPage({ batchId }: { batchId: string }) { return <GovernedProgramShell><Hero eyebrow="OPENLAB · REPORT" title={`Report ${batchId}`} copy="Original-first report presentation with field-level provenance and explicit absence."/><section className={styles.section}><div className={`${styles.shell} ${styles.grid}`}><ReportIdentityHeader state="unavailable"/><UnavailableEvidencePanel title="Report preview unavailable" copy="No original report is registered. No generated instrument graph or reconstructed chromatogram is shown in its place."/><AnalyteTable/><UnavailableEvidencePanel title="Method unavailable" copy="No source-owned analytical method is registered for this report."/><CustodyTimeline/></div></section></GovernedProgramShell>; }

export function OpenLabAdminPage() { return <GovernedProgramShell><Hero eyebrow="OWNER REVIEW · NOT PUBLIC" title="OpenLab command centre." copy="This surface is a private Sites specimen. Identity, authorization and operational data contracts are not approved for Shopper SSR."/><section className={styles.section}><div className={`${styles.shell} ${styles.grid3}`}><Card title="Registry health" copy="Owner-only placeholder; no live operational feed."/><Card title="Source coverage" copy="Owner-only placeholder; no inferred completeness."/><Card title="Review queue" copy="Owner-only placeholder; no public actions."/></div></section></GovernedProgramShell>; }

const checkoutCopy: Record<CheckoutStep,{title:string;copy:string}> = { information:{title:"Your information.",copy:"Review contact and delivery details before continuing."}, delivery:{title:"Choose delivery.",copy:"Available methods and their final cost appear before the order is placed."}, review:{title:"Your product, order value and payment equivalent.",copy:paymentTrustCopy.continuity}, payment:{title:"Make a card payment.",copy:"Enter your payment information in the protected provider step."}, confirmation:{title:"Order received.",copy:"Your order details and next steps stay together."} };
export function CheckoutProgramPage({ step }: { step: CheckoutStep }) { const current=checkoutCopy[step]; return <GovernedProgramShell lane="checkout"><Hero eyebrow={step === "payment" ? "SECURE PAYMENT" : "SECURE CHECKOUT"} title={current.title} copy={current.copy}/><section className={styles.section}><div className={styles.shell}><CheckoutStepIndicator current={step}/><div className={`${styles.grid} ${styles.section}`}>{step === "information" && <><PaymentTrustPrimer/><Card title="Contact and shipping" copy="Review these details before continuing."><div className={styles.form}><label>Email<input readOnly value="customer@example.invalid"/></label><label>Delivery country<input readOnly value="United Kingdom"/></label></div></Card></>}{step === "delivery" && <>{["Tracked delivery","Priority delivery","International tracked"].map(name=><Card copy="Final cost and eligibility appear here when available." key={name} title={name}/>)}</>}{["review","payment"].includes(step) && <CurrencyEqualityLock/>}{step === "review" && <Card title="Full order details" copy="MK-2866 · Ostarine · 15 MG · 90 SERVINGS"><div className={styles.money}><div><span>Products</span><strong>{paymentTrustStudy.customerAmount} GBP</strong></div><div><span>Your order total</span><strong>{paymentTrustStudy.customerAmount} GBP</strong></div></div></Card>}{step === "payment" && <Card title="Secure card payment" copy="Enter the payment details shown by the protected payment step."><div className={styles.form}><label>First name<input readOnly value=""/></label><label>Last name<input readOnly value=""/></label><label>Card number<input readOnly value="•••• •••• •••• ••••"/></label></div><div className={styles.money}><div><span>Payment amount</span><strong>{paymentTrustStudy.settlementAmount} USD</strong></div></div><button className={styles.button} disabled type="button">Pay securely</button></Card>}{step === "confirmation" && <><LifecycleAmountRecord stage="confirmation"/><RestockCard state="active"/><RecommendationCard/></>}</div></div></section></GovernedProgramShell>; }

export function CheckoutProcessingPage() { return <GovernedProgramShell lane="checkout"><Hero eyebrow="CHECKOUT · STATIC STATE" title="Payment status pending." copy="Do not close this window. This candidate makes no provider request and advances no order state."/><section className={styles.section}><div className={styles.shell}><div className={styles.notice}>Awaiting a server-owned terminal projection. Unknown remains unknown.</div></div></section></GovernedProgramShell>; }
export function CheckoutTrackingPage() { return <GovernedProgramShell lane="checkout"><Hero eyebrow="ORDER TRACKING · READ ONLY" title="Track an order." copy="Tracking stages render only from an order projection; this candidate does not advance them."/><section className={styles.section}><div className={styles.shell}><CustodyTimeline stages={["Order reference received","Fulfilment status unavailable","Carrier status unavailable","Delivery confirmation unavailable"]}/></div></section></GovernedProgramShell>; }
export function GrowthRailPage() { return <GovernedProgramShell><Hero eyebrow="PRODUCT CONTINUATION" title="Recommendations and restock, kept together." copy="Explore related products or return to a future restock decision without interrupting the first purchase choice."/><section className={styles.section}><div className={styles.shell}><UpsellContextRail/></div></section></GovernedProgramShell>; }
