"use client";

/* eslint-disable react/jsx-no-target-blank -- same-origin owner route is intentionally opened for unscaled inspection. */

import { useMemo, useRef, useState } from "react";
import { ReviewStudioGallery } from "../design-system/review-studio-gallery";
import styles from "./review-studio.module.css";

type Decision = "approved" | "flagged" | "deferred";
type Family = { id:string; label:string; routes:string[]; representativeRoutes:string[]; mobileStrategy:string; mobileOrder:string[]; desktopOrder:string[]; hiddenOrDisclosed:string[]; horizontalScrollAllowed:boolean; scrollDepthWarningVh:number; compactNavigationRequired:boolean };
type ModuleGroup = { id:string; label:string; exports:string[]; dataOwner:string; runtimeExclusions:string[]; mounts:string[]; emptyState:string; unavailableState:string; errorState:string; mobileStrategy:string; figmaIntent:string };
type DesignSyncRecord = { id:string; codeExport:string; consumingRoutes:string[]; mobileStrategy:string; status:string; desktopNodeId:string|null; mobileNodeId:string|null };
export type ReviewStudioPayload = { schemaVersion:string; status:string; generatedAt:string; sourceGitSha:string; sourceTreeHash:string; designContractHash:string; decisionCount:number; families:Family[]; moduleGroups:ModuleGroup[]; governance:{id:string;label:string;touchTargetPx:number;lightModeOnly:boolean;canonicalPdp:string;canonicalOpenLab:string;ownerOnlyIsAuthenticated:boolean}; routeLedger:{routeCount:number;maturityCounts:Record<string,number>}; designSync:{fileKey:string;modulesPage:{name:string;nodeId:string|null};routesPage:{name:string;nodeId:string|null};records:DesignSyncRecord[]}; visualEvidence:{routeCount:number;widthCount:number;reviewed:number;capturedUnreviewed:number;pending:number;disposition:string}; proofs:Array<{id:string;status:string;detail:string}>; manualReview:{axeIncompleteCount:number;classification:string} };
type DecisionRecord = { decision?:Decision; notes:string };
type Receipt = { schemaVersion:"oluk.champion-review.v1"; designContractHash:string; sourceGitSha:string; sourceTreeHash:string; generatedAt:string; families:Array<{id:string;decision:Decision;representativeRoutes:string[];notes:string}>; moduleGroups:Array<{id:string;decision:Decision;notes:string}>; governance:{decision:"approved"|"flagged";manualIncompleteAcknowledged:boolean;mobileCompactionAcknowledged:boolean} };

function DecisionControl({ value, onChange }: { value:DecisionRecord; onChange:(value:DecisionRecord)=>void }) {
  return <div className={styles.decision}><div>{(["approved","flagged","deferred"] as const).map((decision)=><button aria-pressed={value.decision===decision} data-decision={decision} key={decision} onClick={()=>onChange({...value,decision})} type="button">{decision}</button>)}</div><label>Review notes<textarea onChange={(event)=>onChange({...value,notes:event.target.value})} placeholder="Required when flagged or deferred" value={value.notes}/></label></div>;
}

export function ReviewStudioClient({ payload, initialFamily, initialModule }: { payload:ReviewStudioPayload; initialFamily?:string; initialModule?:string }) {
  const firstFamily=payload.families.find((item)=>item.id===initialFamily)??payload.families[0]; const firstModule=payload.moduleGroups.find((item)=>item.id===initialModule)??payload.moduleGroups[0];
  const [familyId,setFamilyId]=useState(firstFamily.id); const [moduleId,setModuleId]=useState(firstModule.id); const [route,setRoute]=useState(firstFamily.representativeRoutes[0]); const [viewport,setViewport]=useState<1440|390>(1440);
  const [familyDecisions,setFamilyDecisions]=useState<Record<string,DecisionRecord>>({}); const [moduleDecisions,setModuleDecisions]=useState<Record<string,DecisionRecord>>({}); const [governance,setGovernance]=useState({decision:undefined as "approved"|"flagged"|undefined,manualIncompleteAcknowledged:false,mobileCompactionAcknowledged:false}); const [message,setMessage]=useState(""); const importRef=useRef<HTMLInputElement>(null);
  const family=payload.families.find((item)=>item.id===familyId)!; const group=payload.moduleGroups.find((item)=>item.id===moduleId)!;
  const scale=viewport===1440?0.62:1; const previewStyle=useMemo(()=>({width:`${viewport}px`,height:viewport===1440?"900px":"760px",transform:`scale(${scale})`}),[viewport,scale]);
  const figmaHref=(nodeId:string)=>`https://www.figma.com/design/${payload.designSync.fileKey}/Final-Design?node-id=${nodeId.replace(":","-")}`;
  const routeSync=payload.designSync.records.filter((record)=>record.consumingRoutes.some((path)=>path==="/*"||path===route||path.endsWith(":slug")&&route.startsWith(path.split(":")[0])||path.endsWith("/*")&&route.startsWith(path.slice(0,-1))));
  const moduleSync=payload.designSync.records.filter((record)=>group.exports.includes(record.codeExport));
  function chooseFamily(id:string){const next=payload.families.find((item)=>item.id===id)!;setFamilyId(id);setRoute(next.representativeRoutes[0]);}
  function buildReceipt():Receipt|null { const families=payload.families.map((item)=>({id:item.id,decision:familyDecisions[item.id]?.decision,representativeRoutes:item.representativeRoutes,notes:familyDecisions[item.id]?.notes??""})); const groups=payload.moduleGroups.map((item)=>({id:item.id,decision:moduleDecisions[item.id]?.decision,notes:moduleDecisions[item.id]?.notes??""})); const invalid=[...families,...groups].find((item)=>!item.decision||((item.decision==="flagged"||item.decision==="deferred")&&!item.notes.trim())); if(invalid||!governance.decision||!governance.manualIncompleteAcknowledged||!governance.mobileCompactionAcknowledged){setMessage("Complete all 12 decisions, add notes for flagged/deferred items, and acknowledge both governance checks before export.");return null;} return {schemaVersion:"oluk.champion-review.v1",designContractHash:payload.designContractHash,sourceGitSha:payload.sourceGitSha,sourceTreeHash:payload.sourceTreeHash,generatedAt:new Date().toISOString(),families:families as Receipt["families"],moduleGroups:groups as Receipt["moduleGroups"],governance:governance as Receipt["governance"]}; }
  function exportReceipt(){const receipt=buildReceipt();if(!receipt)return;const url=URL.createObjectURL(new Blob([`${JSON.stringify(receipt,null,2)}\n`],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`oluk-champion-review-${payload.sourceTreeHash.slice(0,12)}.json`;anchor.click();URL.revokeObjectURL(url);setMessage("Receipt exported locally. No server, storage, GitHub, runtime, or baseline state was changed.");}
  async function importReceipt(file?:File){if(!file)return;try{const receipt=JSON.parse(await file.text()) as Receipt;if(receipt.schemaVersion!=="oluk.champion-review.v1"||receipt.designContractHash!==payload.designContractHash||receipt.sourceTreeHash!==payload.sourceTreeHash)throw new Error("Receipt does not match this frozen review payload.");setFamilyDecisions(Object.fromEntries(receipt.families.map((item)=>[item.id,{decision:item.decision,notes:item.notes}])));setModuleDecisions(Object.fromEntries(receipt.moduleGroups.map((item)=>[item.id,{decision:item.decision,notes:item.notes}])));setGovernance(receipt.governance);setMessage("Matching receipt imported into memory.");}catch(error){setMessage(error instanceof Error?error.message:"Receipt import failed.");}}
  return <main className={styles.studio} data-owner-only="true" id="main-content"><header className={styles.hero}><span>OWNER REVIEW · NOT AUTHENTICATED · UNPUBLISHED</span><h1>Champion Review Studio</h1><p>Review six route families, five canonical module groups, and one governance/compaction gate. The exhaustive screenshot matrix remains machine evidence.</p><p><a href="/review-studio/pdp-candidates">Open the unselected PDP candidate suite →</a></p><div className={styles.hashes}><code>contract {payload.designContractHash.slice(0,12)}</code><code>tree {payload.sourceTreeHash.slice(0,12)}</code><code>{payload.routeLedger.routeCount} route dispositions</code></div></header>
  <section className={styles.dashboard} aria-labelledby="governance-title"><div><span>01 · GOVERNANCE</span><h2 id="governance-title">Machine evidence, compressed for human review.</h2><p>{payload.visualEvidence.capturedUnreviewed} captured-unreviewed and {payload.visualEvidence.pending} pending cases remain QA evidence—not individual approval tasks.</p></div><div className={styles.badges}>{payload.proofs.map((proof)=><span data-status={proof.status} key={proof.id}><b>{proof.status}</b>{proof.detail}</span>)}<span data-status="MANUAL"><b>MANUAL</b>{payload.manualReview.axeIncompleteCount} axe incompletes; no violations</span></div><div className={styles.governanceDecision}><button aria-pressed={governance.decision==="approved"} onClick={()=>setGovernance({...governance,decision:"approved"})}>Approve governance</button><button aria-pressed={governance.decision==="flagged"} onClick={()=>setGovernance({...governance,decision:"flagged"})}>Flag governance</button><label><input checked={governance.manualIncompleteAcknowledged} onChange={(e)=>setGovernance({...governance,manualIncompleteAcknowledged:e.target.checked})} type="checkbox"/>Acknowledge manual contrast review</label><label><input checked={governance.mobileCompactionAcknowledged} onChange={(e)=>setGovernance({...governance,mobileCompactionAcknowledged:e.target.checked})} type="checkbox"/>Acknowledge mobile compaction review</label></div></section>
  <section className={styles.reviewSection}><header><span>02 · SIX FAMILY DECISIONS</span><h2>Live route-family review</h2></header><nav aria-label="Route families" className={styles.tabs}>{payload.families.map((item)=><button aria-pressed={item.id===familyId} key={item.id} onClick={()=>chooseFamily(item.id)}>{item.label}</button>)}</nav><div className={styles.familyMeta}><div><strong>{family.label}</strong><span>{family.mobileStrategy} · warning after {family.scrollDepthWarningVh} mobile viewports</span></div><div><b>Desktop</b>{family.desktopOrder.join(" → ")}</div><div><b>Mobile</b>{family.mobileOrder.join(" → ")}</div><div><b>Compacts</b>{family.hiddenOrDisclosed.join(" · ")}</div></div><div className={styles.previewToolbar}><label>Template<select onChange={(e)=>setRoute(e.target.value)} value={route}>{family.representativeRoutes.map((path)=><option key={path}>{path}</option>)}</select></label><div><button aria-pressed={viewport===1440} onClick={()=>setViewport(1440)}>1440</button><button aria-pressed={viewport===390} onClick={()=>setViewport(390)}>390</button><a href={route} target="_blank">Open live route</a></div></div>{routeSync.some((record)=>record.desktopNodeId||record.mobileNodeId)?<div className={styles.syncLinks}><strong>Native Figma pair</strong>{routeSync.flatMap((record)=>[record.desktopNodeId?<a href={figmaHref(record.desktopNodeId)} key={`${record.id}-desktop`} target="_blank">{record.id} · 1440</a>:null,record.mobileNodeId?<a href={figmaHref(record.mobileNodeId)} key={`${record.id}-mobile`} target="_blank">{record.id} · 390</a>:null])}</div>:null}<div className={styles.previewFrame} style={{height:`${(viewport===1440?900:760)*scale}px`}}><iframe key={`${route}-${viewport}`} loading="lazy" src={route} style={previewStyle} title={`${family.label} ${viewport}px live preview`}/></div><DecisionControl onChange={(value)=>setFamilyDecisions({...familyDecisions,[family.id]:value})} value={familyDecisions[family.id]??{notes:""}}/></section>
  <section className={styles.reviewSection}><header><span>03 · FIVE MODULE DECISIONS</span><h2>Canonical module groups</h2></header><nav aria-label="Module groups" className={styles.tabs}>{payload.moduleGroups.map((item)=><button aria-pressed={item.id===moduleId} key={item.id} onClick={()=>setModuleId(item.id)}>{item.label}</button>)}</nav><aside className={styles.moduleContract}><strong>{group.exports.join(" · ")}</strong><span>Owner: {group.dataOwner}</span><span>Mounts: {group.mounts.join(" · ")}</span><span>Mobile: {group.mobileStrategy}</span><span>Unavailable: {group.unavailableState}</span><span>Excluded: {group.runtimeExclusions.join(" · ")}</span><span>Figma intent: {group.figmaIntent}</span></aside>{moduleSync.some((record)=>record.desktopNodeId||record.mobileNodeId)?<div className={styles.syncLinks}><strong>Native Figma pair</strong>{moduleSync.flatMap((record)=>[record.desktopNodeId?<a href={figmaHref(record.desktopNodeId)} key={`${record.id}-desktop`} target="_blank">{record.id} · 1440</a>:null,record.mobileNodeId?<a href={figmaHref(record.mobileNodeId)} key={`${record.id}-mobile`} target="_blank">{record.id} · 390</a>:null])}</div>:null}<ReviewStudioGallery groupId={group.id}/><DecisionControl onChange={(value)=>setModuleDecisions({...moduleDecisions,[group.id]:value})} value={moduleDecisions[group.id]??{notes:""}}/></section>
  <section className={styles.export}><span>04 · PORTABLE RECEIPT</span><h2>Export decisions without granting runtime authority.</h2><p>Import/export operates on a local file and in-memory state only. It does not publish, promote, deploy, write to GitHub, or persist in browser storage.</p><div><button onClick={exportReceipt}>Export champion receipt</button><button onClick={()=>importRef.current?.click()}>Import matching receipt</button><input accept="application/json" hidden onChange={(e)=>importReceipt(e.target.files?.[0])} ref={importRef} type="file"/></div><output aria-live="polite">{message}</output></section></main>;
}
