import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const siteRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const repoRoot=path.resolve(siteRoot,"../..");
const readSite=(file)=>readFile(path.join(siteRoot,file),"utf8");

test("OpenLab core is a declared canonical module system",async()=>{const registry=JSON.parse(await readFile(path.join(repoRoot,"authority/OPENLAB-SECTION-MODULE-REGISTRY.json"),"utf8"));assert.equal(registry.runtimeAuthority,"NONE");assert.equal(registry.canonicalNamespace,"/open-lab");assert.ok(registry.modules.length>=18);assert.deepEqual(registry.ownerOnlyRoutes,["/open-lab/admin"]);assert.deepEqual(registry.deferredRoutes,[]);for(const entry of registry.modules){assert.ok(entry.export);assert.ok(entry.dataOwner);assert.ok(entry.mounts.length);assert.ok(entry.mobileStrategy);assert.ok(entry.runtimeExclusions.length);}});

test("P0 and P1 OpenLab routes mount canonical section exports",async()=>{const route=await readSite("app/customer-routes.tsx");for(const component of ["OpenLabHeroLight","OpenLabWayfinding","EvidenceRecordExplainer","OpenLabRegistryArchive","OpenLabRecordDetail","OpenLabDossierComposition","OpenLabMethodologyPipeline","OpenLabSourceChain","OpenLabComparison"])assert.match(route,new RegExp(`<${component}\\b`),component);});

test("OpenLab section modules stay presentation-only and responsive",async()=>{const [source,css]=await Promise.all([readSite("app/design-system/openlab-sections.tsx"),readSite("app/design-system/openlab-sections.module.css")]);assert.doesNotMatch(source,/fetch\(|XMLHttpRequest|WebSocket|localStorage|sessionStorage|order_prepare|payment_bridge|complete_payment/i);assert.match(source,/EvidenceStatusChip/);assert.match(source,/OpenLabRegistryArchive/);assert.match(css,/@media\(max-width:900px\)/);assert.match(css,/@media\(max-width:600px\)/);assert.match(css,/overflow-x:auto/);assert.doesNotMatch(css,/#(?:[0-9a-f]{3}){1,2}\b/i);});

test("the MK-2866 product experience is compiled deterministically from the public OpenLab projection shape",async()=>{const [compiler,output,component,dossier,compoundRoute]=await Promise.all([readSite("scripts/compile-openlab-product-experience.mjs"),readSite("app/design-system/openlab-product-experience.json"),readSite("app/design-system/openlab-product-experience.tsx"),readSite("app/design-system/openlab-sections.tsx"),readSite("app/open-lab/compound/[slug]/page.tsx")]);const experience=JSON.parse(output);assert.match(compiler,/OpenLabPublicProjection\.v2/);assert.equal(experience.sourceContract,"OpenLabPublicProjection.v2");assert.match(experience.sourceHash,/^[a-f0-9]{64}$/);assert.match(experience.contentHash,/^[a-f0-9]{64}$/);assert.equal(experience.sourceAttribution.recordId,experience.record.id);assert.equal(experience.product.slug,"mk-2866");assert.equal(experience.record.batchCode,"OL2201");assert.equal(experience.visualizations.purity.displayValue,">99%");assert.equal(experience.visualizations.concentration.testedValue,"16.02 mg");assert.equal(experience.interactionContract.chartPolicy,"numeric bars and source-owned tabular values only");for(const view of ["record","report history","label comparison","analytes","batch timeline","availability","source context"])assert.match(component,new RegExp(view));assert.match(component,/tableFallback/);assert.match(component,/ArrowRight/);assert.match(component,/data-openlab-state="unavailable"/);assert.doesNotMatch(component,/fetch\(|XMLHttpRequest|WebSocket|localStorage|sessionStorage|chromatogram/i);assert.match(dossier,/OpenLabProductExperience/);assert.match(dossier,/productSlug={productSlug}/);assert.match(compoundRoute,/productSlug={product.slug}/);});

test("modular packet uses the canonical PDP and OpenLab namespaces",async()=>{const packet=await readFile(path.join(repoRoot,"FIGMA_TO_CODEX_PACKET__MODULAR_SECTION_REGISTRY.md"),"utf8");assert.match(packet,/PRODUCT DETAIL PAGE \(`\/product\/:slug`\)/);assert.doesNotMatch(packet,/PRODUCT DETAIL PAGE \(`\/shop\/:slug`\)/);assert.match(packet,/Canonical namespace: \/open-lab/);assert.doesNotMatch(packet,/\/openlab\/admin/);});
