import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { validateCompactionContract, validateTouchTargets } from "../scripts/proof/mobile-compaction-contract.mjs";

const siteRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."); const repoRoot=path.resolve(siteRoot,"../.."); const read=async(file)=>readFile(path.join(repoRoot,file),"utf8");
test("review studio exposes exactly twelve portable owner decisions",async()=>{const contract=JSON.parse(await read("authority/REVIEW-STUDIO-CONTRACT.json"));assert.equal(contract.families.length,6);assert.equal(contract.moduleGroups.length,5);assert.equal(contract.decisionCount,12);assert.equal(contract.runtimeAuthority,"NONE");const client=await read("sites/oluk-experience-lab/app/review-studio/review-studio-client.tsx");assert.match(client,/oluk\.champion-review\.v1/);assert.match(client,/URL\.createObjectURL/);assert.doesNotMatch(client,/localStorage|sessionStorage|fetch\(|XMLHttpRequest|WebSocket/i);});
test("studio is owner-only, noindex, and absent from customer navigation",async()=>{const routes=await read("sites/oluk-experience-lab/app/design-system/site-route-data.mjs");const layout=await read("sites/oluk-experience-lab/app/review-studio/layout.tsx");const experience=await read("sites/oluk-experience-lab/app/experience-lab.tsx");assert.match(routes,/review-studio.+owner-review/);assert.match(layout,/index:false,follow:false/);assert.doesNotMatch(experience,/href="\/review-studio"/);});
test("mobile contract rejects missing strategy, false reorder, and undersized targets",()=>{const valid={mobileStrategy:"reorder",mobileOrder:["b","a"],desktopOrder:["a","b"],scrollDepthWarningVh:12};assert.deepEqual(validateCompactionContract(valid),[]);assert.ok(validateCompactionContract({...valid,mobileStrategy:"unknown"}).length);assert.ok(validateCompactionContract({...valid,mobileOrder:["a","b"]}).some((failure)=>failure.includes("does not change")));assert.equal(validateTouchTargets([{width:43,height:44},{width:44,height:44},{width:50,height:30}],44).length,2);});
test("all program modules declare compaction and touch contracts",async()=>{const registry=JSON.parse(await read("authority/PROGRAM-COMPONENT-REGISTRY.json"));for(const component of registry.components){assert.ok(component.responsive.mobileStrategy);assert.equal(component.responsive.touchTargetPx,44);}});
