/* eslint-disable @next/next/no-img-element -- explicit local product render, dimensions and loading policy are audited. */
import Link from "next/link";
import type { FrontierProductRecord } from "./frontier-content";
import { actualProductMedia, frontierFaq, frontierProducts, productBySlug, stackPresentations } from "./frontier-content";
import { EvidenceStatusChip, RecommendationCard, RestockCard, UpsellContextRail } from "./program-components";
import styles from "./frontier-sections.module.css";

export function FrontierShell({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <main className={styles.page}><header className={styles.hero}><span>{eyebrow}</span><h1>{title}</h1><p>Built as a complete, composable Olympus Labs UK customer experience. Product, OpenLab and commerce pathways use one visual system at every width.</p></header>{children}</main>}
export function ProductHero({product}:{product:FrontierProductRecord}){const media=actualProductMedia[product.slug];return <section className={styles.productHero}><div className={styles.productVisual}>{media&&<img alt={`${product.name} finished product`} decoding="async" height={media.height} loading="eager" src={media.src} width={media.width}/>}<span>{product.series}</span><strong>{product.name}</strong><em>{product.alias}</em><small>{product.strength} · {product.servings}</small></div><div><span className={styles.eyebrow}>PRODUCT DECISION</span><h1>{product.name}</h1><p className={styles.alias}>{product.alias}</p><p>{product.summary}</p><dl className={styles.specs}><div><dt>Strength</dt><dd>{product.strength}</dd></div><div><dt>Servings</dt><dd>{product.servings}</dd></div><div><dt>Purity</dt><dd>{product.purity}</dd></div><div><dt>SKU</dt><dd>{product.sku}</dd></div></dl><div className={styles.decision}><strong>{product.price}</strong><button type="button">Add to bag</button></div></div></section>}
export function ProductNarrative({product}:{product:FrontierProductRecord}){return <><section className={styles.twoCol}><article><span className={styles.eyebrow}>RESEARCH PROFILE</span><h2>{product.alias}, in context.</h2><p>{product.researchProfile}</p></article><article><span className={styles.eyebrow}>PRODUCT GUIDANCE</span><h2>Clarity before the next step.</h2><p>{product.guidance}</p><p>{product.considerations}</p></article></section><section className={styles.tabSet}><details open><summary>Product detail</summary><p>{product.summary}</p></details><details><summary>Evidence</summary><EvidenceStatusChip state="verified-evidence"/><p>Browse the OpenLab presentation for source paths, record structure and report views.</p></details><details><summary>Reviews</summary><p>Customer review presentation is available when it is ready to be shown in the experience.</p></details></section></>}
export function ProductContinuation({product}:{product:FrontierProductRecord}){const related=product.related.map((slug)=>productBySlug[slug]).filter(Boolean);return <section className={styles.continuation}><div><span className={styles.sectionLabel}>Build your stack</span><h2>Build more from your {product.name} stack.</h2><p>Choose your next result: more strength and lean mass, heavyweight size and power, or stronger growth and recovery.</p></div><div className={styles.cardGrid}>{related.map((item)=><Link className={styles.productCard} href={`/product/${item.slug}`} key={item.slug}><span>{item.series}</span><strong>{item.name}</strong><small>{item.strength} · {item.price}</small></Link>)}</div><UpsellContextRail/></section>}
export function StackExplorer(){return <section className={styles.stackExplorer}><header><span className={styles.sectionLabel}>Build your stack</span><h2>Start with the result. Build the products around it.</h2><p>Choose your goal, compare the Good, Better and Best build, then make the stack your own.</p></header><div className={styles.stackGrid}>{stackPresentations.map((stack)=><article key={stack.goal}><span className={styles.goalChip}>{stack.goal}</span><h3>{stack.headline}</h3><strong>{stack.hero}</strong><p>{stack.promise}</p><small>Also consider {stack.alternates.join(" · ")}</small><ol>{stack.tiers.map((tier)=><li key={tier}>{tier}</li>)}</ol></article>)}</div></section>}
export function ProductCollection({products=frontierProducts}:{products?:ReadonlyArray<FrontierProductRecord>}){return <section className={styles.collection}><div className={styles.collectionHead}><span className={styles.eyebrow}>CATALOGUE</span><h2>Find the right product route.</h2><p>Filter by product family, goal, form, servings and availability in the live Shop experience.</p></div><div className={styles.catalogueGrid}>{products.map((product)=><Link className={styles.catalogueCard} href={`/product/${product.slug}`} key={product.slug}><span>{product.family}</span><h3>{product.name}</h3><p>{product.alias}</p><strong>{product.strength}</strong><small>{product.servings} · {product.price}</small></Link>)}</div></section>}
export function GrowthModules(){return <section className={styles.growth}><div><span className={styles.eyebrow}>CONTINUATION</span><h2>Returns, restock and value coaching.</h2><p>The growth layer uses the same recommendation contracts across PDP, bag, confirmation and account routes.</p></div><div className={styles.growthGrid}><RecommendationCard/><RestockCard state="due-soon"/><article className={styles.offer}><span>ORDER VALUE</span><h3>£7 more for free UK delivery</h3><p>Progress coaching is visible, compact and never obscures the order total.</p></article></div></section>}
export function CheckoutLifecycle({stage}:{stage:string}){const payment=stage==="review"||stage==="payment"||stage==="confirmation";return <section className={styles.checkout}><div className={styles.checkoutSteps}>{["Bag","Information","Delivery","Review","Payment","Confirmation"].map((label,index)=><span data-active={label.toLowerCase()===stage || (stage==="confirmation"&&index<6)} key={label}>{index+1}. {label}</span>)}</div><div className={styles.checkoutGrid}><article><span className={styles.eyebrow}>{stage.toUpperCase()}</span><h2>{stage==="confirmation"?"Your order total":"Your product, order value and payment equivalent."}</h2><p>{stage==="confirmation"?"Your order total of £128.97 GBP was processed and paid as its fixed USD equivalent of $175.01 USD.":"You are paying the USD equivalent of the displayed GBP amount."}</p>{payment&&<div className={styles.currency}><strong>$175.01 <small>USD</small></strong><span>=</span><strong>£128.97 <small>GBP</small></strong></div>}<button type="button">Continue</button></article><aside><span>ORDER VALUE</span><dl><div><dt>Products</dt><dd>£128.97</dd></div><div><dt>Tracked delivery</dt><dd>Included</dd></div><div><dt>Your order total</dt><dd>£128.97 GBP</dd></div></dl></aside></div></section>}
export function AccountHub({mode}:{mode:string}){return <section className={styles.account}><header><span className={styles.eyebrow}>ACCOUNT · {mode.toUpperCase()}</span><h1>{mode==="dashboard"?"Your Olympus overview.":`${mode.replaceAll("-"," ")} workspace.`}</h1><p>Orders, saved products, restock prompts and account preferences are composed from the same compact dashboard modules.</p></header><div className={styles.accountGrid}><article><span>ORDER HISTORY</span><h3>MK-2866</h3><p>Recent order, tracking and receipt views stay connected.</p></article><article><span>RESTOCK LAB</span><h3>Due soon</h3><p>Cycle-aware presentation with pause and reminder states.</p></article><article><span>LOYALTY</span><h3>320 points</h3><p>Tier progress, referral and account activity presentation.</p></article></div></section>}
export function SupportContent({kind}:{kind:"about"|"faq"|"bundle"|"tool"}){if(kind==="faq")return <section className={styles.faq}><span className={styles.eyebrow}>HELP CENTRE</span><h1>Clear answers, organised by route.</h1>{frontierFaq.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section>;if(kind==="bundle")return <><FrontierShell eyebrow="BUNDLE BUILDER" title="Build a collection that reads clearly."><StackExplorer/><GrowthModules/></FrontierShell></>;return <FrontierShell eyebrow={kind==="about"?"ABOUT OLYMPUS":"OPENLAB TOOL"} title={kind==="about"?"A clearer product and laboratory story.":"OpenLab research workspace."}><section className={styles.twoCol}><article><h2>Designed for confident discovery.</h2><p>Our visual system connects product detail, testing stories, UK delivery and customer support into one coherent path.</p></article><article><h2>Built for mobile compaction.</h2><p>Priority information remains visible while comparison and reference material moves into orderly disclosures or intentional horizontal tables.</p></article></section></FrontierShell>}
