import type { ProductFixture } from "./product-fixtures";
import { mk2866Fixture } from "./product-fixtures";
import { ProductMediaChamber } from "./product-media-chamber";
import { EvidenceStatusChip } from "./program-components";
import styles from "./pdp-sections.module.css";

export type PdpSectionProps = Readonly<{ product?:ProductFixture }>;

export function ProductMediaGallery({product=mk2866Fixture}:PdpSectionProps){return <section aria-label={`${product.name} product media`} className={styles.gallery} data-component="ProductMediaGallery"><div className={styles.mediaMeta}><span>FINISHED PRODUCT</span><span>SKU {product.sku}</span></div><ProductMediaChamber context="hero" media={product.media} priority/><div className={styles.viewIndex} role="list" aria-label="Available product views"><span aria-current="true" role="listitem">Front</span><span role="listitem">1 OF 1</span></div></section>}

export function ProductDetailDisclosure({product=mk2866Fixture}:PdpSectionProps){const form=product.qualitativeFacts.find((fact)=>fact.kind==="form")?.value;return <section className={styles.details} data-component="ProductDetailDisclosure" id="product-details"><header><span>PRODUCT DETAIL</span><h2>Everything needed for a clear product decision.</h2><p>Label truth, product composition and customer guidance remain grouped without competing with the purchase decision.</p></header><div className={styles.disclosureGrid}><details open><summary>Product facts</summary><dl><div><dt>Series</dt><dd>{product.series}</dd></div><div><dt>Strength</dt><dd>{product.strength}</dd></div><div><dt>Servings</dt><dd>{product.servings}</dd></div><div><dt>SKU</dt><dd>{product.sku}</dd></div></dl></details><details><summary>Composition</summary><dl><div><dt>Compound</dt><dd>{product.alias}</dd></div><div><dt>Form</dt><dd>{form}</dd></div><div><dt>Purity</dt><dd>{product.purity}</dd></div></dl></details><details><summary>Guidance and warnings</summary><p>Review the product label and the applicable customer information before making a purchase decision.</p></details></div></section>}

export function ProductEvidenceSnapshot({product=mk2866Fixture}:PdpSectionProps){return <section className={styles.evidence} data-component="ProductEvidenceSnapshot" data-section-id="evidence-snapshot" id="lab-records"><div><span>OPENLAB SNAPSHOT</span><h2>Third-Party Tested.</h2><p>The product decision stays connected to its OpenLab pathway, with the approved product specifications carried through intact.</p><a href={product.evidencePath}>Open the MK-2866 evidence pathway →</a></div><div className={styles.evidenceFacts}><EvidenceStatusChip state="verified-evidence"/><dl><div><dt>Product</dt><dd>{product.name}</dd></div><div><dt>Compound</dt><dd>{product.alias}</dd></div><div><dt>Purity</dt><dd>{product.purity}</dd></div><div><dt>SKU</dt><dd>{product.sku}</dd></div></dl></div></section>}

export function MobileDecisionSummary({product=mk2866Fixture}:PdpSectionProps){return <aside aria-label="Mobile product decision summary" className={styles.mobileDecision} data-component="MobileDecisionSummary"><div><span>{product.name}</span><strong>{product.price}</strong></div><a href="#purchase" style={{color:"var(--oluk-text-on-inverse)"}}>View purchase options</a></aside>}
