import Link from "next/link";

type SupportSurfaceKind = "shipping-returns" | "faq" | "international" | "gift-cards" | "cookies" | "refunds" | "sitemap" | "legal";

const content: Record<SupportSurfaceKind, { eyebrow: string; title: string; copy: string; cards: Array<[string, string, string]> }> = {
  "shipping-returns": { eyebrow: "DELIVERY AND RETURNS", title: "Know what happens from checkout to delivery.", copy: "Find the delivery information, tracking path and return guidance you need before or after an order.", cards: [["Delivery", "Choose a delivery option at checkout and keep the order total clear before payment.", "Choose delivery"], ["Tracking", "Follow the order progress from dispatch through delivery.", "Track an order"], ["Returns", "Start with the order details and keep every next step clear.", "View return guidance"]] },
  faq: { eyebrow: "HELP CENTRE", title: "Get the answer and keep moving.", copy: "Browse the essential product, delivery and OpenLab questions in one calm, useful place.", cards: [["Product questions", "Start with the product detail, metrics and the relevant OpenLab record.", "Browse products"], ["Delivery help", "Review delivery choices before payment and tracking after dispatch.", "Delivery information"], ["OpenLab", "Find a batch, compare products or open a report.", "Visit OpenLab"]] },
  international: { eyebrow: "INTERNATIONAL", title: "Shop Olympus wherever your next order starts.", copy: "Explore delivery availability, order preparation and support information for international customers.", cards: [["Delivery availability", "Review destination-specific options at checkout.", "Choose a destination"], ["Order value", "Keep the selected customer currency clear all the way to payment.", "See payment information"], ["Support", "Get help with an existing order or a wholesale enquiry.", "Contact support"]] },
  "gift-cards": { eyebrow: "GIFT CARDS", title: "Give someone a stronger next step.", copy: "Choose a gift amount, send it when the moment is right, and let the recipient build their own product direction.", cards: [["Choose an amount", "Pick the value that works for the occasion.", "Choose value"], ["Send it your way", "Keep delivery and recipient details simple.", "Plan delivery"], ["Shop the range", "Point them to clear product facts and useful comparisons.", "Browse products"]] },
  cookies: { eyebrow: "COOKIE SETTINGS", title: "Keep your choices clear.", copy: "Read how cookies support the current customer experience and where to manage your preferences.", cards: [["Essential", "The basics that help the site work as expected.", "Read essentials"], ["Experience", "Settings that help the site remember useful preferences.", "Manage preferences"], ["More information", "Read the full privacy information alongside this summary.", "Privacy information"]] },
  refunds: { eyebrow: "REFUNDS", title: "Start a refund request with the order in view.", copy: "Open the order details first, then review the refund amount and the next step for the original payment.", cards: [["Find the order", "Open the relevant order and keep the product and payment amount together.", "View orders"], ["Review the amount", "The original GBP total and fixed USD equivalent stay visible.", "View refund details"], ["Get support", "Ask for help when the order needs a closer look.", "Contact support"]] },
  sitemap: { eyebrow: "SITEMAP", title: "Find what you came for.", copy: "Move directly into the shop, OpenLab, your account or customer support.", cards: [["Shop", "Browse product families, goals and product comparisons.", "Shop now"], ["OpenLab", "Find a batch, read a record or compare compounds.", "Explore OpenLab"], ["Your account", "Return to orders, restock and saved decisions.", "Open account"]] },
  legal: { eyebrow: "LEGAL INFORMATION", title: "The information behind your order.", copy: "Open the current legal information for the customer experience and review the details that apply.", cards: [["Privacy", "Read how information is handled.", "Privacy policy"], ["Terms", "Read the current terms and conditions.", "Terms and conditions"], ["Cookies", "Review cookie settings and choices.", "Cookie settings"]] },
};

const links: Record<string, string> = { "Choose delivery": "/checkout/delivery", "Track an order": "/checkout/tracking", "View return guidance": "/refunds", "Browse products": "/shop", "Delivery information": "/delivery", "Visit OpenLab": "/open-lab", "Choose a destination": "/checkout/information", "See payment information": "/checkout/review", "Contact support": "/contact", "Choose value": "/gift-cards", "Plan delivery": "/checkout/information", "Read essentials": "/cookies", "Manage preferences": "/cookies", "Privacy information": "/privacy", "View orders": "/account/orders", "View refund details": "/refunds", "Shop now": "/shop", "Explore OpenLab": "/open-lab", "Open account": "/account/dashboard", "Privacy policy": "/privacy", "Terms and conditions": "/terms", "Cookie settings": "/cookies" };

export function SupportSurface({ kind }: { kind: SupportSurfaceKind }) {
  const surface = content[kind];
  return <main className="support-surface"><header className="page-hero"><div className="shell"><span className="eyebrow">{surface.eyebrow}</span><h1>{surface.title}</h1><p>{surface.copy}</p></div></header><div className="shell support-surface-grid">{surface.cards.map(([title, copy, action], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h2>{title}</h2><p>{copy}</p><Link href={links[action]}>{action} →</Link></article>)}</div></main>;
}
